ALTER TABLE `db_yzhao248`.`REGISTRATION` 
ADD CONSTRAINT `FK_REGISTRATION_Course_Id_Semester_Section`
  FOREIGN KEY (`SEMESTER` , `SECTION` , `COURSE_ID`)
  REFERENCES `db_yzhao248`.`COURSE` (`SEMESTER` , `SECTION` , `COURSE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
